### PR TITLE
w6 warmup tasks complete

### PR DESCRIPTION
**Pull request by Shinseeker**

### CODE REVIEW

**Comment by Shinseeker** [comment]
Hard work pays off!

**Comment by Shinseeker** [comment]
HI chris,

I did not run into that issue. Let me check your code.

**Comment by cjfernanders1986** [comment]
https://github.com/is210-2015-fall-01/is210-week-06-warmup/pull/1

**Comment by sdavlenov** [comment]
Hey Chris Im having the same issue! Any luck fixing it?

**Pull request merged**
